experiment: basketball
model: SNLDS #REDSDS
dataset: basketball
# seg_labels: true
# only_segmentation: True
d_min: 20 # duration 
d_max: 50 # duration 
batch_size: 32
context_length: 10000 #not used
prediction_length: 30
#freq: H # not used
x_dim: 30 # 8
obs_dim: 20
model_dir: ./results/basketball/{timestamp}/models/
train_history_dir: ./results/basketball/{timestamp}/train_history/
forecasts_dir: ./results/basketball/{timestamp}/forecasts/
log_dir: ./results/basketball/{timestamp}/logs/
log_steps: 500
save_steps: 500
num_categories: 10
warmup_steps_lr: 500 #2000
num_steps: 10000 #20000   # must exceed warmup_steps_lr 
num_samples: 5 #10 #30
objective: elbov2
flat_learning_rate: false
warmup_start_lr: 5.e-3 #5.e-5
learning_rate: 0.002 #0.0002
grad_clip_norm: 10.
weight_decay: 1.e-5
initial_switch:
  mlp_hiddendim: 8
discrete_transition:
  takes_x: true
  takes_y: true
continuous_transition:
  model_type: nonlinear
  tied_cov: false
  trainable_cov: true
  fixed_sigma: .0003 #0.02
  max_scale: .0003 #0.25
  scale_nonlinearity: softplus
  mlp_hiddendim: 8
emission:
  model_type: nonlinear
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.003 #0.02
  max_scale:  0.003 #0.25
  scale_nonlinearity: softplus
inference: 
  tied_cov: false
  trainable_cov: true
  fixed_sigma: .0003  # 0.02
  max_scale: .0003 #0.25
  scale_nonlinearity: softplus
  embedder: brnn  # transformer or brnn
# BRNN params
  embedding_rnndim: 16
  embedding_rnnlayers: 1
# Transformer params
  embedding_trans_usepe: true
  embedding_trans_nhead: 1
  embedding_trans_embdim: 4
  embedding_trans_mlpdim: 16
  embedding_trans_nlayers: 1
# Causal RNN
  use_causal_rnn: true
  causal_rnndim: 16
# MLP
  mlp_hiddendim: 32
initial_state:
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 0.25
  scale_nonlinearity: softplus
  mlp_hiddendim: 8
control:
  mlp_hiddendim: 64
  has_ctrl: false
  z: false
  x: false
  inference: false
  emb_dim: 0
  feat_dim: 0
  n_staticfeat: 0
  n_timefeat: 0
transform_target: false 
transform_only_scale: false
use_jacobian: false
forecast:
  num_samples: 20
switch_t_annealing: true
switch_t_init: 100.
switch_t_min: 10.
switch_t_annealing_rate: 0.95
switch_t_annealing_steps: 100
switch_t_annealing_kickin_steps: 5000
dur_t_annealing: true
dur_t_init: 10.
dur_t_min: 1.
dur_t_annealing_rate: 0.95
dur_t_annealing_steps: 100
dur_t_annealing_kickin_steps: 5000
cont_ent_anneal: 1.0
# Unused or inconsequential
xent_annealing: false
xent_init: 100.
xent_rate: 0.95
xent_steps: 50
xent_kickin_steps: 2000